name: CD

on:
  push:
    tags:
      - 'v*-dev*'  # 例如 v1.0.0-dev

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: sh build.sh

      - name: Get version from tag
        id: get_version
        run: |
          # 从 tag (例如 v1.0.0-dev) 提取版本号 (v1.0.0)
          VERSION=$(echo ${{ github.ref_name }} | sed 's/-dev.*//')
          
          # 检查对应的版本文件是否存在
          if [ ! -f "versions/${VERSION}.md" ]; then
            echo "Error: Version file versions/${VERSION}.md not found"
            exit 1
          fi
          
          echo "release_version=$VERSION" >> $GITHUB_ENV
          
          # 读取版本文件内容，编码内容为 Base64
          CONTENT=$(base64 -w 0 "versions/${VERSION}.md")
          echo "release_content=$CONTENT" >> $GITHUB_ENV

      - name: Decode Release Content
        run: |
          # Decode the Base64 content
          echo ${{ env.release_content }} | base64 -d > decoded_content.txt
        shell: bash

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ env.release_version }}
          body: $(cat decoded_content.txt)
          draft: false
          prerelease: true
