name: Make sure new PRs are sent to dev

on:
  pull_request_target:
    types: [ opened, reopened, edited ]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: main
          exclude: dev
          change-to: dev
          comment: |
            Your PR was set to target `main`, PRs should be target `dev`
            The base branch of this PR has been automatically changed to `dev`
            Please check that there are no merge conflicts

            
